apiVersion: v1
kind: Service
metadata:
  name: kartat-dl
  labels:
    app: kartat-dl
spec:
  ports:
    - port: 80
  selector:
    app: kartat-dl
---
kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: default
  name: kartat-dl
  labels:
    app: kartat-dl
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kartat-dl
  template:
    metadata:
      labels:
        app: kartat-dl
    spec:
      containers:
        - name: kartat-dl
          image: nginx:stable
          ports:
            - name: web
              containerPort: 80
          volumeMounts:
            - mountPath: /usr/share/nginx/html
              name: kartat-dl-volume
      volumes:
        - name: kartat-dl-volume
          hostPath:
            path: /opt/mtk2garmin-publish
            type: Directory
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-kartat-dl
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: kartat-dl.hylly.org
      http:
        paths:
          - path: /
            backend:
              serviceName: kartat-dl
              servicePort: 80
  tls:
    - hosts:
        - kartat-dl.hylly.org
      secretName: hylly-org-prod-tls