name: mtk2garmin-converter docker image

on:
  push:
    paths: 
      - 'mtk2garmin-converter/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build and publish mtk2garmin-converter to Registry
      uses: docker/build-push-action@v2
      with:
        repository: teemupel/mtk2garmin-converter
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        file: Dockerfile
        context: mtk2garmin-converter
