name: mtk2garmin-converter docker image

on:
  push:
    paths: 
      - 'mtk2garmin-converter/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Build and publish mtk2garmin-converter to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: teemupel/mtk2garmin-converter
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        snapshot: true
        workdir: mtk2garmin-converter 
        dockerfile: Dockerfile 
